BOARD_SIZE = 9
OB_SIZE = 1
STRING_MAX = int(0.8 * BOARD_SIZE * (BOARD_SIZE - 1) + 5)
NEIGHBOR_MAX = STRING_MAX
STRING_LIB_MAX = (BOARD_SIZE + OB_SIZE * 2) ** 2
STRING_POS_MAX = (BOARD_SIZE + OB_SIZE * 2) ** 2
NEIGHBOR_END = NEIGHBOR_MAX - 1
LIBERTY_END = STRING_LIB_MAX - 1
STRING_END = STRING_POS_MAX - 1

PASS = 0
RESIGN = -1

GTP_X_COORDINATE = 'IABCDEFGHJKLMNOPQRSTUVWXYZ'
